version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    groups:
      minor-and-patch:
        patterns: ["*"]
        dependency-type: "production"
        update-types: ["minor","patch"]
      major:
        patterns: ["*"]
        dependency-type: "production"
        update-types: ["major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"